output: docs/
clean: true
xcodebuild_arguments:
  - -workspace
  - Testing/SwiftyDSB.xcworkspace
  - -scheme
  - SwiftyDSB
author: Noim
author_urL: https://noim.io
module: SwiftyDSB
github_url: https://github.com/TheNoim/DSBAPISwift